### ISSUE TITLE
Update-NuGet Error.

### ISSUE THREAD

**Issue by prateekjain0608** [bobfamiliar/microservices-iot-azure#1]
When the file 
microservices-iot-azure/HandsOnLabs/Microservices/Config/Automation/02-Build-ConfigM.ps1
is run in Powershell, followed strictly according to the manual, an error is generated for the command 
Update-Nuget at line 120 of this file. Thereon, every Update-NuGet function generates a similar error.
The error is:

WARNING: FAILED to build "c:\users\Account\source\repos\microservices-iot-azure-master\Microservices\Config\Public\Interface\IC
onfigPublic.sln". Please check the build log "C:\Users\Roopam\AppData\Local\Temp\IConfigPublic.sln.msbuild.log" for details.
VERBOSE: IConfigPublic build failed. Check the log file for errors.
nuget.exe : Unable to find version '1.2.5812.17959' of package 'ConfigModels'.
At C:\users\Account\source\repos\microservices-iot-azure-master\Automation\Common\Invoke-UpdateNuGet.psm1:19 char:5
-     & $nuget $nugetparams
-     ~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (Unable to find ...'ConfigModels'.:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

**Comment by bobfamiliar** [comment]
Have you configured the repo's NuGet package folder in Visual Studio as a location for Visual Studio to find nuget packages? See Chapter 5, Page 86 for details on how to configure the build environment. If you till have an issue after that let me know.

**Comment by roopamk** [comment]
Thanks the problem was solved!
