### ISSUE TITLE
Publish Website Error

### ISSUE THREAD

**Issue by roopamk** [bobfamiliar/microservices-iot-azure#2]
The Lab 1 of the manual is executed without errors, but when the given end points are used to test the microservice deployments, it shows an error and does not display the desired web page.

**Comment by bobfamiliar** [comment]
First, as I am reviewing the lab, I see there is a typo in Step 8 of lab workbook 1. It says to repeat step 6. It should read repeat step 7. I updated the lab workbook.

This will be difficult to support on this thread. Connect with me on Linked-in and I will be able to better support. -bob
